---
- name: Install packages
  apt:
    name:
      - mysql-server
      - python-mysqldb

- name: Edit configuration file
  template:
    dest: /etc/mysql/{{ item }}
    mode: 0644
    src: "{{ item }}.j2"
  with_items:
    - conf.d/client.cnf
    - mysql.conf.d/mysqld.cnf
  notify: Restart MySQL

- name: Launch and enable
  service:
    enabled: yes
    name: mysql
    state: started

- name: Change root password
  mysql_user:
    host: localhost
    password: "{{ mysql_root_password }}"
    user: root

- name: Create /root/.my.cnf
  template:
    dest: /root/.my.cnf
    mode: 600
    src: root/my.cnf.j2

- name: Creat a root user for remote connection
  mysql_user:
    host: "%"
    name: root
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL"
  when: mysql_root_remote_connection_enabled

- name: Remove a root user for remote connection
  mysql_user:
    host: "%"
    name: root
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL"
    state: absent
  when: not mysql_root_remote_connection_enabled
