---
- name: Create database
  mysql_db: name={{ db_name }}

- name: Create database user
  mysql_user:
    host: "{{ db_host }}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"

- name: Install mysql2
  gem:
    name: mysql2
    executable: "{{ rbenv_install_dir }}/shims/gem"

- name: Execute yarn install
  shell: /usr/bin/yarn install
  args:
    chdir: /vagrant/{{ project_name }}

- name: Create project
  shell: "{{ rbenv_install_dir}}/shims/rails new {{ project_name }} -d mysql --webpack=vue"
  args:
    chdir: /vagrant

- name: Edit Gemfile
  template:
    dest: /vagrant/{{ project_name }}/Gemfile
    mode: 0644
    src: Gemfile.j2

- name: Execute bundle install
  shell: "{{ rbenv_install_dir}}/shims/bundle install"
  args:
    chdir: /vagrant/{{ project_name }}

- lineinfile:
    path: /vagrant/{{ project_name }}/config/database.yml
    regexp: '^\s\susername\: root$'
    line: '  username: {{ db_user }}'

- lineinfile:
    path: /vagrant/{{ project_name }}/config/database.yml
    regexp: '^\s\spassword\:$'
    line: '  password: {{ db_password }}'

- name: Execute gemerate
  shell: |
    {{ rbenv_install_dir}}/shims/rails webpacker:install
    {{ rbenv_install_dir}}/shims/rails webpacker:install:vue
    {{ rbenv_install_dir}}/shims/rails generate devise:install
    {{ rbenv_install_dir}}/shims/rails generate devise user
    {{ rbenv_install_dir}}/shims/rails generate devise:views users
  args:
    chdir: /vagrant/{{ project_name }}