---
- name: Edit Gemfile
  template:
    dest: /vagrant/{{ project_name }}/Gemfile
    mode: 0644
    src: Gemfile.j2

- name: Edit database.yml
  replace:
    path: /vagrant/{{ project_name }}/config/database.yml
    regexp: 'encoding\:\sunicode$'
    replace: "encoding: unicode\n  username: {{ db_user }}\n  password: {{ db_password }}"

- name: Execute yarn install
  shell: /usr/bin/yarn install --check-files
  args:
    chdir: /vagrant/{{ project_name }}

- name: Execute bundle install
  shell: "{{ rbenv_install_dir}}/shims/bundle install"
  args:
    chdir: /vagrant/{{ project_name }}

- name: Restart PostgeSQL
  service:
    name: postgresql
    state: restarted

- name: Execute database rollback
  become: yes
  shell: "{{ rbenv_install_dir}}/shims/rails db:rollback"
  args:
    chdir: /vagrant/{{ project_name }}

- name: Execute database migrate
  become: yes
  shell: "{{ rbenv_install_dir}}/shims/rails db:migrate"
  args:
    chdir: /vagrant/{{ project_name }}

- name: Edit configuration files
  template:
    dest: "/vagrant/{{ project_name }}/{{ item }}"
    mode: 0777
    src: "{{ item }}.j2"
  with_items:
    - Procfile
    - Procfile.dev
    - bin/server