---
- name: Execute yarn install
  shell: /usr/bin/yarn install
  args:
    chdir: /vagrant

- name: Execute bundle install
  shell: "{{ rbenv_install_dir}}/shims/bundle install"
  args:
    chdir: /vagrant

- name: Restart PostgeSQL
  service:
    name: postgresql
    state: restarted

- name: Execute database migrate
  become: yes
  shell: "{{ rbenv_install_dir}}/shims/rails db:migrate:reset"
  args:
    chdir: /vagrant

- name: Edit configuration files
  template:
    dest: "/vagrant/{{ item }}"
    mode: 0777
    src: "{{ item }}.j2"
  with_items:
    - Procfile
    - Procfile.dev
    - bin/server