---
- name: Create database
  postgresql_db:
    encoding: UTF-8
    lc_collate: C
    lc_ctype: C
    name: "{{ db_name }}"
    template: template0
  become: yes
  become_user: postgres

- name: Create user of database
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: ALL
  become: yes
  become_user: postgres