---
- name: Add Postgresql12 repository to apt
  become: yes
  become_user: root
  shell: |
    sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
    apt-get install curl ca-certificates
    curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
    apt update

- name: Install packagese
  apt:
    name:
      - postgresql-12
      - python-psycopg2

- name: Edit environment
  become: yes
  template:
    dest: /etc
    mode: 0644
    src: environment.j2

- name: Edit configuration file
  template:
    dest: "/etc/postgresql/12/main/{{ item }}"
    group: postgres
    mode: 0640
    owner: postgres
    src: "{{ item }}.j2"
  with_items:
    - postgresql.conf
    - pg_hba.conf
  notify: Restart PostgreSQL

- name: Launch and enable
  service:
    enabled: yes
    name: postgresql
    state: started
